# Generated by Django 4.1.2 on 2022-11-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("position", models.CharField(max_length=50)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.department",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contact", name="phone", field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name="TourData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tourName", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.employee",
                    ),
                ),
            ],
            options={"ordering": ["tourName"],},
        ),
    ]
