# Generated by Django 4.1.2 on 2022-11-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_department_employee_alter_contact_phone_tourdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourdata",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
