# Generated by Django 4.1.2 on 2022-11-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_tourdata_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourdata", name="price", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="tourdata",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="slider-1.jpg", null=True, upload_to=""
            ),
        ),
    ]
